/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MySecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_10": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_100": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_101": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_102": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_103": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_104": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_105": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_106": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_107": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_108": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_109": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_11": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_110": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_111": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_112": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_113": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_114": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_115": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_116": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_117": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_118": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_119": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_12": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_120": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_121": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_122": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_123": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_124": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_125": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_126": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_127": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_128": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_129": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_13": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_130": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_131": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_132": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_133": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_134": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_135": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_136": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_137": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_138": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_139": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_14": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_140": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_141": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_142": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_143": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_144": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_145": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_146": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_147": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_148": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_149": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_15": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_150": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_151": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_152": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_153": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_154": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_155": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_156": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_157": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_158": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_159": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_16": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_160": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_161": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_162": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_163": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_164": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_165": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_166": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_167": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_168": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_169": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_17": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_170": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_171": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_172": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_173": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_174": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_175": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_176": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_177": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_178": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_179": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_18": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_180": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_181": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_182": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_183": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_184": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_185": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_186": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_187": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_188": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_189": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_19": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_190": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_191": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_192": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_193": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_194": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_195": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_196": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_197": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_198": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_199": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_20": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_200": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_21": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_22": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_23": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_24": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_25": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_26": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_27": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_28": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_29": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_30": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_31": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_32": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_33": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_34": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_35": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_36": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_37": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_38": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_39": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_4": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_40": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_41": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_42": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_43": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_44": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_45": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_46": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_47": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_48": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_49": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_5": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_50": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_51": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_52": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_53": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_54": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_55": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_56": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_57": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_58": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_59": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_6": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_60": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_61": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_62": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_63": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_64": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_65": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_66": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_67": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_68": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_69": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_7": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_70": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_71": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_72": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_73": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_74": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_75": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_76": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_77": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_78": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_79": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_8": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_80": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_81": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_82": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_83": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_84": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_85": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_86": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_87": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_88": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_89": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_9": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_90": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_91": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_92": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_93": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_94": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_95": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_96": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_97": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_98": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MySecret_99": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
